### ISSUE TITLE
"Scrypted NVR Beta has expired."

### ISSUE THREAD

**Issue by JoshKelleway** [koush/nvr.scrypted.app#16]
all of my scrypted NVR instances are returning the message "Scrypted NVR Beta has expired" when accessing them through the web GUI - 4 instances all displaying the same issue.

**Comment by koush** [comment]
This was fixed earlier today. Please update your plugin and reload the browser, or close + reopen iOS app.

**Comment by JoshKelleway** [comment]
had updated the plugins, but not reloaded the browser.. issue solved, thankyou

**Comment by maxedmini** [comment]
I have done all available updates but still showing for me via the home assistant install?

**Comment by koush** [comment]
@maxedmini close the browser fully and reopen. short of that, restart your PC. might be safari being very stubborn about cache.
